### ISSUE TITLE
Got JSON decode exception

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#136]
I experienced a JSON decoding crash. Here's the error I got with sensitive info replaced:

> matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event: Unknown websocket message: \"user_updated\"", jsonDecodeExceptionJSON = "{\"team_id\":\"\",\"channel_id\":\"\",\"user_id\":\"4txfpxbojfnb9e8d4higtphkco\",\"event\":\"user_updated\",\"data\":{\"user\":{\"id\":\"4txfpxbojfnb9e8d4higtphkco\",\"create_at\":1474394270273,\"update_at\":1476980710618,\"delete_at\":0,\"username\":\"<username>\",\"auth_data\":\"\",\"auth_service\":\"\",\"email\":\"<user@domain.com>\",\"nickname\":\"\",\"first_name\":\"<first name>\",\"last_name\":\"<last name>\",\"roles\":\"\",\"locale\":\"en\"}}}\n"}

**Comment by jtdaugherty** [comment]
This was because the API package and the client didn't know about `user_updated` events. That's fixed now (although the client doesn't do anything with them yet).

**Comment by cdrage** [comment]
Hey @jtdaugherty I'm still getting this issue:
```
Authenticating...
Loading channels for team "centos"...
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "mmGetJSONBody: Error in $: expected Seq a, encountered Object", jsonDecodeExceptionJSON = "{\"channels\":[{\"id\":\"7ii9r7nbi7r79dcykajcipwh9c\",\"create_at\":1482344373786,\"update_at\":1482344373786,\"delete_at\":0,\"team_id\":\"\",\"type\":\"D\",\"display_name\":\"\",\"name\":\"3gcaimpdr3gkujuhn3n4zhjcma__aiqzhbz8cpyjxf8u4reqj8as1h\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":0,\"total_msg_count\":0,\"extra_update_at\":1482344373786,\"creator_id\":\"\"},{\"id\":\"kkpizii5qbd7pmhu46i35bkuuo\",\"create_at\":1482992429938,\"update_at\":1482992429938,\"delete_at\":0,\"team_id\":\"\",\"type\":\"D\",\"display_name\":\"\",\"name\":\"aiqzhbz8cpyjxf8u4reqj8as1h__u5dic1hjapbaxepjzp5geg1j3c\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1482992841847,\"total_msg_count\":3,\"extra_update_at\":1482992429938,\"creator_id\":\"\"},{\"id\":\"xyckeuo743nytchaew8x3qj7fo\",\"create_at\":1476992885130,\"update_at\":1476992885130,\"delete_at\":0,\"team_id\":\"9nqq69f17tgkmmbwtnfkzqnhhy\",\"type\":\"O\",\"display_name\":\"Off-Topic\",\"name\":\"off-topic\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1480531109829,\"total_msg_count\":24,\"extra_update_at\":1483547857928,\"creator_id\":\"\"},{\"id\":\"pjtbmng5wpfpxkdzcrmdp6otwc\",\"create_at\":1476992885122,\"update_at\":1476992885122,\"delete_at\":0,\"team_id\":\"9nqq69f17tgkmmbwtnfkzqnhhy\",\"type\":\"O\",\"display_name\":\"Town Square\",\"name\":\"town-square\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1479909791822,\"total_msg_count\":28,\"extra_update_at\":1483547857924,\"creator_id\":\"\"}],\"members\":{\"7ii9r7nbi7r79dcykajcipwh9c\":{\"channel_id\":\"7ii9r7nbi7r79dcykajcipwh9c\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":0,\"msg_count\":0,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1482344373787},\"kkpizii5qbd7pmhu46i35bkuuo\":{\"channel_id\":\"kkpizii5qbd7pmhu46i35bkuuo\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":1482992841847,\"msg_count\":3,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1482992841847},\"pjtbmng5wpfpxkdzcrmdp6otwc\":{\"channel_id\":\"pjtbmng5wpfpxkdzcrmdp6otwc\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":1479909791822,\"msg_count\":28,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1479909791822},\"xyckeuo743nytchaew8x3qj7fo\":{\"channel_id\":\"xyckeuo743nytchaew8x3qj7fo\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":0,\"msg_count\":0,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1481817314362}}}"}
```

This is using the latest `git clone` of the matterhorn-api and matterhorn. Any ideas?

**Comment by cdrage** [comment]
@jtdaugherty nvm, seems to be an unrelated issue regarding something else. i'm going to open up a separate issue.
